import { CRMDetailSheet, RecordTable } from "@/components/crm/CRMRecords";
import { DetailPair, DialogActions, FieldGrid, FilterSelect, MoneyField, SearchFilters, SelectField, TextAreaField, TextField } from "@/components/crm/CRMForms";
import { CreateButton, EmptyState, ErrorPanel, LoadingPanel, PageHeader, Pagination, StatusBadge, money, shortDate, useSearchShortcut } from "@/components/crm/CRMPrimitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgePoundSterling, Building2, CheckCircle2, Pencil, Target, UserRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearch } from "wouter";
import { toast } from "sonner";

const statuses = ["New", "Contacted", "Qualified", "Nurturing", "Converted", "Disqualified"] as const;
const editableStatuses = statuses.filter(value => value !== "Converted");
type LeadForm = { firstName: string; lastName: string; companyName: string; jobTitle: string; email: string; phone: string; propertyId: string; ownerId: string; source: string; businessType: string; potentialRoomNights: number; status: typeof statuses[number]; estimatedValueCents: number; notes: string };
type ConvertForm = { opportunityName: string; valueCents: number; probability: number; expectedCloseDate: string; nextStep: string; nextActionAt: string; companyId: string; contactId: string };
const emptyLead: LeadForm = { firstName: "", lastName: "", companyName: "", jobTitle: "", email: "", phone: "", propertyId: "", ownerId: "", source: "", businessType: "Corporate account", potentialRoomNights: 0, status: "New", estimatedValueCents: 0, notes: "" };
const emptyConvert: ConvertForm = { opportunityName: "", valueCents: 0, probability: 10, expectedCloseDate: "", nextStep: "", nextActionAt: "", companyId: "", contactId: "" };

export default function Leads() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [businessType, setBusinessType] = useState(""); const [propertyId, setPropertyId] = useState("");
  const [editorOpen, setEditorOpen] = useState(false); const [convertOpen, setConvertOpen] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [selectedId, setSelectedId] = useState<number | null>(null); const [form, setForm] = useState<LeadForm>(emptyLead); const [convertForm, setConvertForm] = useState<ConvertForm>(emptyConvert);
  const searchRef = useSearchShortcut(); const routeSearch = useSearch(); const utils = trpc.useUtils(); const references = trpc.metadata.references.useQuery();
  const query = trpc.leads.list.useQuery({ page, pageSize: 20, search, status: status as typeof statuses[number] || undefined, businessType: businessType as any || undefined, propertyId: propertyId ? Number(propertyId) : undefined, sort: "updated" });
  const detail = trpc.leads.get.useQuery({ id: selectedId! }, { enabled: selectedId !== null });
  const create = trpc.leads.create.useMutation({ onSuccess: () => saved("Lead captured") }); const update = trpc.leads.update.useMutation({ onSuccess: () => saved("Lead updated") });
  const convert = trpc.leads.convert.useMutation({ onSuccess: result => { toast.success("Lead converted to an Opportunity", { description: `Opportunity #${result.opportunityId} is ready in Prospecting.` }); setConvertOpen(false); setSelectedId(null); utils.leads.invalidate(); utils.opportunities.invalidate(); utils.companies.invalidate(); utils.contacts.invalidate(); utils.dashboard.invalidate(); } });
  const propertyOptions = references.data?.properties.map(item => ({ value: String(item.id), label: item.name })) ?? []; const ownerOptions = references.data?.assignees.map(item => ({ value: String(item.id), label: item.name || item.email || "JMK user" })) ?? []; const typeOptions = (references.data?.taxonomy.opportunityTypes ?? []).map(value => ({ value, label: value }));
  useEffect(() => setPage(1), [search, status, businessType, propertyId]);
  useEffect(() => { if (!references.data) return; const params = new URLSearchParams(routeSearch); if (params.get("create") === "1") { openCreate(); window.history.replaceState({}, "", window.location.pathname); } else if (params.get("open")) { setSelectedId(Number(params.get("open"))); window.history.replaceState({}, "", window.location.pathname); } }, [references.data, routeSearch]);
  function set<K extends keyof LeadForm>(key: K, value: LeadForm[K]) { setForm(current => ({ ...current, [key]: value })); } function setConvert<K extends keyof ConvertForm>(key: K, value: ConvertForm[K]) { setConvertForm(current => ({ ...current, [key]: value })); }
  function saved(message: string) { toast.success(message); setEditorOpen(false); setEditingId(null); utils.leads.invalidate(); utils.dashboard.invalidate(); }
  function openCreate() { setEditingId(null); setForm({ ...emptyLead, propertyId: propertyOptions.length === 1 ? propertyOptions[0].value : "", ownerId: ownerOptions.length === 1 ? ownerOptions[0].value : "" }); setEditorOpen(true); }
  function openEdit() { const row = detail.data?.lead; if (!row) return; setEditingId(row.id); setForm({ firstName: row.firstName, lastName: row.lastName, companyName: row.companyName || "", jobTitle: row.jobTitle || "", email: row.email || "", phone: row.phone || "", propertyId: String(row.propertyId), ownerId: String(row.ownerId), source: row.source || "", businessType: row.businessType, potentialRoomNights: row.potentialRoomNights, status: row.status, estimatedValueCents: row.estimatedValueCents, notes: row.notes || "" }); setEditorOpen(true); }
  function openConversion() { const row = detail.data?.lead; if (!row) return; setConvertForm({ ...emptyConvert, opportunityName: row.companyName ? `${row.companyName} — ${row.businessType}` : `${row.firstName} ${row.lastName} — ${row.businessType}`, valueCents: row.estimatedValueCents, nextStep: "Confirm requirements and agree the next commercial action", nextActionAt: new Date(Date.now() + 86400000).toISOString().slice(0, 16) }); setConvertOpen(true); }
  function submit(event: FormEvent) { event.preventDefault(); const payload = { firstName: form.firstName, lastName: form.lastName, companyName: form.companyName || null, jobTitle: form.jobTitle || null, email: form.email || null, phone: form.phone || null, propertyId: Number(form.propertyId), ownerId: Number(form.ownerId), source: form.source || null, businessType: form.businessType as any, potentialRoomNights: form.potentialRoomNights, status: form.status, estimatedValueCents: form.estimatedValueCents, notes: form.notes || null }; if (editingId) update.mutate({ id: editingId, ...payload }); else create.mutate(payload); }
  function submitConversion(event: FormEvent) { event.preventDefault(); if (!selectedId) return; convert.mutate({ id: selectedId, opportunityName: convertForm.opportunityName, valueCents: convertForm.valueCents, probability: convertForm.probability, expectedCloseDate: convertForm.expectedCloseDate ? new Date(convertForm.expectedCloseDate) : null, nextStep: convertForm.nextStep, nextActionAt: convertForm.nextActionAt ? new Date(convertForm.nextActionAt) : null, companyId: convertForm.companyId ? Number(convertForm.companyId) : null, contactId: convertForm.contactId ? Number(convertForm.contactId) : null }); }
  const rows = useMemo(() => query.data?.items ?? [], [query.data]);
  const companyOptions = (references.data?.companies ?? []).map(item => ({ value: String(item.id), label: item.label })); const contactOptions = (references.data?.contacts ?? []).map(item => ({ value: String(item.id), label: item.label }));
  return <>
    <PageHeader eyebrow="Lead intelligence" title="Leads" description="Capture every enquiry, qualify its hotel value, and convert it into a clear next commercial action." action={<CreateButton label="Capture lead" onClick={openCreate} />} />
    <SearchFilters value={search} onChange={setSearch} searchRef={searchRef} activeFilters={[status, businessType, propertyId].filter(Boolean).length} onClear={() => { setStatus(""); setBusinessType(""); setPropertyId(""); }}><FilterSelect value={propertyId} onChange={setPropertyId} options={propertyOptions} placeholder="All properties" className="w-[180px]" /><FilterSelect value={businessType} onChange={setBusinessType} options={typeOptions} placeholder="All business types" className="w-[180px]" /><FilterSelect value={status} onChange={setStatus} options={statuses.map(value => ({ value, label: value }))} placeholder="All statuses" /></SearchFilters>
    {query.isLoading ? <LoadingPanel rows={7} /> : query.error ? <ErrorPanel message={query.error.message} onRetry={() => query.refetch()} /> : !rows.length ? <div className="surface"><EmptyState icon={Target} title="No leads in this view" description="Capture a new hotel enquiry or broaden the current search and filters." action={<CreateButton label="Capture lead" onClick={openCreate} />} /></div> : <div className="surface overflow-hidden"><RecordTable columns={["Lead", "Property", "Business type", "Potential", "Source", "Status"]}>{rows.map(row => <tr key={row.id} onClick={() => setSelectedId(row.id)} className="cursor-pointer border-b border-[#edf0ed] transition-colors last:border-0 hover:bg-[#f8faf7]"><td className="px-4 py-3.5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#f0ede5] text-[#8a6b32]"><UserRound className="h-4 w-4" /></div><div><p className="text-xs font-semibold">{row.firstName} {row.lastName}</p><p className="mt-1 text-[12px] text-muted-foreground">{row.companyName || row.email || "New relationship"}</p></div></div></td><td className="px-4 py-3.5 text-xs">{row.propertyName}</td><td className="px-4 py-3.5 text-xs">{row.businessType}</td><td className="px-4 py-3.5"><p className="text-xs font-semibold">{money(row.estimatedValueCents)}</p><p className="mt-1 text-[12px] text-muted-foreground">{row.potentialRoomNights.toLocaleString()} room nights</p></td><td className="px-4 py-3.5 text-xs">{row.source || "—"}</td><td className="px-4 py-3.5"><StatusBadge value={row.status} /></td></tr>)}</RecordTable><Pagination page={query.data?.page ?? page} pageSize={query.data?.pageSize ?? 20} total={query.data?.total ?? 0} onPage={setPage} /></div>}
    <Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto rounded-[1.5rem] p-6"><DialogHeader><DialogTitle className="font-display text-2xl">{editingId ? "Edit lead" : "Capture lead"}</DialogTitle><DialogDescription>Record enough context to qualify quickly and move the enquiry forward.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-3 space-y-5"><FieldGrid><TextField label="First name" value={form.firstName} onChange={value => set("firstName", value)} required /><TextField label="Last name" value={form.lastName} onChange={value => set("lastName", value)} required /><TextField label="Company or organisation" value={form.companyName} onChange={value => set("companyName", value)} /><TextField label="Job title" value={form.jobTitle} onChange={value => set("jobTitle", value)} /><TextField label="Email" type="email" value={form.email} onChange={value => set("email", value)} /><TextField label="Phone" value={form.phone} onChange={value => set("phone", value)} /><SelectField label="Property" value={form.propertyId} onChange={value => set("propertyId", value)} options={propertyOptions} required /><SelectField label="Owner" value={form.ownerId} onChange={value => set("ownerId", value)} options={ownerOptions} required /><SelectField label="Business type" value={form.businessType} onChange={value => set("businessType", value)} options={typeOptions} required /><SelectField label="Status" value={form.status} onChange={value => set("status", value as LeadForm["status"])} options={editableStatuses.map(value => ({ value, label: value }))} /><TextField label="Lead source" value={form.source} onChange={value => set("source", value)} /><TextField label="Potential room nights" type="number" min={0} value={form.potentialRoomNights} onChange={value => set("potentialRoomNights", Number(value) || 0)} /><MoneyField label="Estimated value" valueCents={form.estimatedValueCents} onChange={value => set("estimatedValueCents", value)} /></FieldGrid><TextAreaField label="Qualification notes" value={form.notes} onChange={value => set("notes", value)} rows={5} /><DialogActions onCancel={() => setEditorOpen(false)} saving={create.isPending || update.isPending} disabled={!form.firstName || !form.lastName || !form.propertyId || !form.ownerId} submitLabel={editingId ? "Save lead" : "Capture lead"} /></form></DialogContent></Dialog>
    <CRMDetailSheet open={selectedId !== null} onOpenChange={open => !open && setSelectedId(null)} title={detail.data ? `${detail.data.lead.firstName} ${detail.data.lead.lastName}` : "Lead profile"} eyebrow={detail.data?.propertyName || "Hotel enquiry"} loading={detail.isLoading} error={detail.error?.message} action={<div className="flex gap-2">{detail.data?.lead.status !== "Converted" && detail.data?.lead.status !== "Disqualified" && <Button size="sm" onClick={openConversion} className="rounded-xl bg-[#ae8240] text-white hover:bg-[#987037]"><ArrowRight className="mr-2 h-3.5 w-3.5" />Convert</Button>}<Button variant="outline" size="sm" onClick={openEdit} className="rounded-xl bg-white"><Pencil className="mr-2 h-3.5 w-3.5" />Edit</Button></div>}>
      {detail.data && <div className="space-y-7"><div className="rounded-2xl bg-[#173a2e] p-5 text-white"><p className="text-[12px] font-semibold uppercase tracking-[0.15em] text-white/55">Estimated commercial value</p><p className="mt-2 font-display text-3xl">{money(detail.data.lead.estimatedValueCents)}</p><p className="mt-2 text-xs text-white/60">{detail.data.lead.potentialRoomNights.toLocaleString()} potential room nights · {detail.data.lead.businessType}</p></div><div className="grid gap-2 sm:grid-cols-2"><DetailPair label="Status" value={<StatusBadge value={detail.data.lead.status} />} /><DetailPair label="Owner" value={detail.data.ownerName} /><DetailPair label="Company" value={detail.data.lead.companyName} /><DetailPair label="Job title" value={detail.data.lead.jobTitle} /><DetailPair label="Email" value={detail.data.lead.email} /><DetailPair label="Phone" value={detail.data.lead.phone} /><DetailPair label="Source" value={detail.data.lead.source} /><DetailPair label="Created" value={shortDate(detail.data.lead.createdAt)} /><DetailPair label="Qualification notes" value={detail.data.lead.notes} wide /></div>{detail.data.lead.convertedOpportunityId && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-emerald-700" /><div><p className="text-xs font-semibold text-emerald-900">Converted successfully</p><p className="mt-1 text-[13px] text-emerald-700">Opportunity #{detail.data.lead.convertedOpportunityId} was created in Prospecting.</p></div></div></div>}</div>}
    </CRMDetailSheet>
    <Dialog open={convertOpen} onOpenChange={setConvertOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto rounded-[1.5rem] p-6"><DialogHeader><div className="mb-2 grid h-11 w-11 place-items-center rounded-2xl bg-[#eee5d5] text-[#8c6b31]"><BadgePoundSterling className="h-5 w-5" /></div><DialogTitle className="font-display text-2xl">Convert into an Opportunity</DialogTitle><DialogDescription>This creates or links the account and contact, then opens a new Opportunity in <strong>Prospecting</strong>.</DialogDescription></DialogHeader><form onSubmit={submitConversion} className="mt-3 space-y-5"><FieldGrid><TextField label="Opportunity name" value={convertForm.opportunityName} onChange={value => setConvert("opportunityName", value)} required /><MoneyField label="Opportunity value" valueCents={convertForm.valueCents} onChange={value => setConvert("valueCents", value)} required /><TextField label="Probability" type="number" min={0} max={100} value={convertForm.probability} onChange={value => setConvert("probability", Number(value) || 0)} required /><TextField label="Expected close" type="date" value={convertForm.expectedCloseDate} onChange={value => setConvert("expectedCloseDate", value)} /><SelectField label="Link existing company (optional)" value={convertForm.companyId} onChange={value => setConvert("companyId", value)} options={companyOptions} placeholder="Create from lead" /><SelectField label="Link existing contact (optional)" value={convertForm.contactId} onChange={value => setConvert("contactId", value)} options={contactOptions} placeholder="Create from lead" /><TextField label="Next action date" type="datetime-local" value={convertForm.nextActionAt} onChange={value => setConvert("nextActionAt", value)} /></FieldGrid><TextAreaField label="Mandatory next action" value={convertForm.nextStep} onChange={value => setConvert("nextStep", value)} rows={3} /><DialogActions onCancel={() => setConvertOpen(false)} saving={convert.isPending} submitLabel="Convert lead" disabled={!convertForm.opportunityName || !convertForm.nextStep} /></form></DialogContent></Dialog>
  </>;
}
