import { useAuth } from "@/_core/hooks/useAuth";
import { DetailPair, DialogActions, FieldGrid, FilterSelect, SearchFilters, SelectField, TextAreaField, TextField } from "@/components/crm/CRMForms";
import { CRMDetailSheet, RecordTable } from "@/components/crm/CRMRecords";
import { CreateButton, EmptyState, ErrorPanel, LoadingPanel, PageHeader, StatusBadge, shortDate } from "@/components/crm/CRMPrimitives";
import { PropertyLogo } from "@/components/BrandIdentity";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import type { AppRouter } from "../../../server/routers";
import type { inferRouterOutputs } from "@trpc/server";
import { CalendarRange, CheckCircle2, Eye, FilePenLine, Pencil, Send, Sparkles } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type Row = inferRouterOutputs<AppRouter>["weeklyUpdates"]["list"][number];
type Form = { propertyId: string; ownerId: string; weekCommencing: string; keyWins: string; businessPotential: string; keyActivity: string; corporateUpdates: string; groupUpdates: string; eventTradeActivity: string; completedActions: string; nextWeekPriorities: string; isGroupVisible: boolean };
const emptyForm: Form = { propertyId: "", ownerId: "", weekCommencing: mondayInput(new Date()), keyWins: "", businessPotential: "", keyActivity: "", corporateUpdates: "", groupUpdates: "", eventTradeActivity: "", completedActions: "", nextWeekPriorities: "", isGroupVisible: true };

export default function WeeklyUpdates() {
  const { user } = useAuth(); const [propertyId, setPropertyId] = useState(""); const [ownerId, setOwnerId] = useState(""); const [status, setStatus] = useState(""); const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [selected, setSelected] = useState<Row | null>(null); const [form, setForm] = useState<Form>(emptyForm);
  const utils = trpc.useUtils(); const refs = trpc.metadata.references.useQuery(); const query = trpc.weeklyUpdates.list.useQuery({ propertyId: propertyId ? Number(propertyId) : undefined, ownerId: ownerId ? Number(ownerId) : undefined, status: status as "Draft" | "Submitted" || undefined });
  const create = trpc.weeklyUpdates.create.useMutation({ onSuccess: () => saved("Weekly update created") }); const update = trpc.weeklyUpdates.update.useMutation({ onSuccess: () => saved("Weekly update saved") }); const submitUpdate = trpc.weeklyUpdates.submit.useMutation({ onSuccess: () => { toast.success("Weekly update submitted"); setSelected(null); utils.weeklyUpdates.invalidate(); utils.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const draftQuery = trpc.weeklyUpdates.generateDraft.useQuery(
    { propertyId: form.propertyId ? Number(form.propertyId) : undefined, ownerId: form.ownerId ? Number(form.ownerId) : undefined, weekCommencing: new Date(`${form.weekCommencing}T12:00:00`) },
    { enabled: false },
  );
  async function generateDraft() {
    const { data, error } = await draftQuery.refetch();
    if (error) { toast.error(error.message); return; }
    if (!data) return;
    setForm(current => ({
      ...current,
      keyWins: data.keyWins || current.keyWins,
      businessPotential: data.businessPotential || current.businessPotential,
      keyActivity: data.keyActivity || current.keyActivity,
      corporateUpdates: data.corporateUpdates || current.corporateUpdates,
      eventTradeActivity: data.eventTradeActivity || current.eventTradeActivity,
      completedActions: data.completedActions || current.completedActions,
      nextWeekPriorities: data.nextWeekPriorities || current.nextWeekPriorities,
    }));
    toast.success("Draft generated from this week's activity — review before saving");
  }
  const propertyOptions = refs.data?.properties.map(item => ({ value: String(item.id), label: item.name })) ?? []; const ownerOptions = refs.data?.assignees.map(item => ({ value: String(item.id), label: item.name || item.email || "JMK user" })) ?? [];
  const rows = useMemo(() => query.data ?? [], [query.data]);
  useEffect(() => { if (!refs.data) return; const params = new URLSearchParams(window.location.search); if (params.get("create") === "1") { openCreate(); window.history.replaceState({}, "", window.location.pathname); } }, [refs.data]);
  function set<K extends keyof Form>(key: K, value: Form[K]) { setForm(current => ({ ...current, [key]: value })); }
  function openCreate() { setEditingId(null); setForm({ ...emptyForm, propertyId: propertyOptions.length === 1 ? propertyOptions[0].value : "", ownerId: user ? String(user.id) : "", weekCommencing: mondayInput(new Date()) }); setEditorOpen(true); }
  function openEdit(row = selected) { if (!row) return; setEditingId(row.id); setForm({ propertyId: String(row.propertyId), ownerId: String(row.ownerId), weekCommencing: inputDate(row.weekCommencing), keyWins: row.keyWins || "", businessPotential: row.businessPotential || "", keyActivity: row.keyActivity || "", corporateUpdates: row.corporateUpdates || "", groupUpdates: row.groupUpdates || "", eventTradeActivity: row.eventTradeActivity || "", completedActions: row.completedActions || "", nextWeekPriorities: row.nextWeekPriorities || "", isGroupVisible: row.isGroupVisible }); setEditorOpen(true); }
  function saved(message: string) { toast.success(message); setEditorOpen(false); setEditingId(null); utils.weeklyUpdates.invalidate(); utils.dashboard.invalidate(); }
  function submit(event: FormEvent) { event.preventDefault(); const payload = { propertyId: Number(form.propertyId), ownerId: Number(form.ownerId), weekCommencing: new Date(`${form.weekCommencing}T12:00:00`), keyWins: form.keyWins || null, businessPotential: form.businessPotential || null, keyActivity: form.keyActivity || null, corporateUpdates: form.corporateUpdates || null, groupUpdates: form.groupUpdates || null, eventTradeActivity: form.eventTradeActivity || null, completedActions: form.completedActions || null, nextWeekPriorities: form.nextWeekPriorities || null, isGroupVisible: form.isGroupVisible }; if (editingId) update.mutate({ id: editingId, ...payload }); else create.mutate(payload); }
  const canEditSelected = selected && (user?.role === "admin" || selected.ownerId === user?.id) && (selected.status === "Draft" || user?.role === "admin");

  return <div className="page-enter max-w-[1500px]"><PageHeader eyebrow="Commercial cadence" title="Weekly updates" description="Capture hotel wins, opportunity signals, completed actions, and next-week priorities in one consistent group reporting rhythm." action={<CreateButton label="New weekly update" onClick={openCreate} />} />
    <section className="surface mb-4 overflow-hidden"><div className="border-b border-[#dce5ee] bg-[#002460] px-5 py-5 text-white sm:px-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/10 text-[#6cccd8]"><CalendarRange className="h-5 w-5" /></span><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-white/50">One trusted commercial record</p><h2 className="mt-1 font-display text-xl">Property reporting that rolls up naturally</h2><p className="mt-1 max-w-2xl text-[11px] leading-5 text-white/60">Draft privately, submit when ready, and share concise property intelligence with the wider group without parallel spreadsheets.</p></div></div></div></section>
    <SearchFilters value="" onChange={() => {}} activeFilters={[propertyId, ownerId, status].filter(Boolean).length} onClear={() => { setPropertyId(""); setOwnerId(""); setStatus(""); }}><FilterSelect value={propertyId} onChange={setPropertyId} options={propertyOptions} placeholder="All properties" className="w-[190px]" /><FilterSelect value={ownerId} onChange={setOwnerId} options={ownerOptions} placeholder="All owners" className="w-[170px]" /><FilterSelect value={status} onChange={setStatus} options={[{ value: "Draft", label: "Draft" }, { value: "Submitted", label: "Submitted" }]} placeholder="All statuses" /></SearchFilters>
    {query.isLoading || refs.isLoading ? <LoadingPanel rows={7} /> : query.error || refs.error ? <ErrorPanel message={(query.error || refs.error)?.message} onRetry={() => { query.refetch(); refs.refetch(); }} /> : !rows.length ? <div className="surface"><EmptyState icon={FilePenLine} title="No weekly updates in this view" description="Start the reporting rhythm with a concise update for one of your assigned properties." action={<CreateButton label="Create update" onClick={openCreate} />} /></div> : <div className="surface overflow-hidden"><RecordTable columns={["Week", "Property", "Owner", "Commercial signal", "Visibility", "Status"]}>{rows.map(row => <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer border-b border-[#e8edf3] transition-colors last:border-0 hover:bg-[#f7fafc]"><td className="px-4 py-3.5"><p className="text-xs font-semibold">Week of {shortDate(row.weekCommencing)}</p><p className="mt-1 text-[9px] text-muted-foreground">Updated {shortDate(row.updatedAt)}</p></td><td className="px-4 py-3.5"><div className="flex min-w-[190px] items-center gap-2.5"><PropertyLogo propertyName={row.propertyName} /><span className="text-[11px] font-semibold leading-4">{row.propertyName}</span></div></td><td className="px-4 py-3.5 text-xs">{row.ownerName || "—"}</td><td className="max-w-[320px] px-4 py-3.5"><p className="truncate text-xs">{row.keyWins || row.businessPotential || row.keyActivity || "Update awaiting detail"}</p><p className="mt-1 text-[9px] text-muted-foreground">{row.keyWins ? "Key win" : row.businessPotential ? "Business potential" : "Commercial activity"}</p></td><td className="px-4 py-3.5"><StatusBadge value={row.isGroupVisible ? "Group visible" : "Private"} /></td><td className="px-4 py-3.5"><StatusBadge value={row.status} /></td></tr>)}</RecordTable></div>}

    <Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto rounded-[1.5rem] p-6"><DialogHeader><DialogTitle className="font-display text-2xl">{editingId ? "Edit weekly update" : "New weekly update"}</DialogTitle><DialogDescription>Use short, specific commercial notes. Submitted updates become part of the property and group reporting record.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-3 space-y-5"><FieldGrid><SelectField label="Property" value={form.propertyId} onChange={value => set("propertyId", value)} options={propertyOptions} required /><SelectField label="Owner" value={form.ownerId} onChange={value => set("ownerId", value)} options={ownerOptions} required /><TextField label="Week commencing" type="date" value={form.weekCommencing} onChange={value => set("weekCommencing", value)} required /><div className="flex min-h-[66px] items-center justify-between rounded-xl border border-[#d9e3ed] bg-[#f7fafc] px-4"><div><p className="text-[11px] font-semibold">Group visible</p><p className="mt-1 text-[9px] text-muted-foreground">Share after submission</p></div><Switch checked={form.isGroupVisible} onCheckedChange={value => set("isGroupVisible", value)} /></div></FieldGrid><Button type="button" variant="outline" onClick={generateDraft} disabled={!form.propertyId || !form.ownerId || draftQuery.isFetching} className="w-full rounded-xl border-[#c3d0c8] bg-[#f7faf7] text-[#47735f] hover:bg-[#eef4e9]"><Sparkles className="mr-2 h-3.5 w-3.5" />{draftQuery.isFetching ? "Generating…" : "Generate draft from this week's activity"}</Button><div className="grid gap-4 md:grid-cols-2"><TextAreaField label="Key wins" value={form.keyWins} onChange={value => set("keyWins", value)} rows={4} /><TextAreaField label="Business potential" value={form.businessPotential} onChange={value => set("businessPotential", value)} rows={4} /><TextAreaField label="Key activity" value={form.keyActivity} onChange={value => set("keyActivity", value)} rows={4} /><TextAreaField label="Corporate updates" value={form.corporateUpdates} onChange={value => set("corporateUpdates", value)} rows={4} /><TextAreaField label="Group updates" value={form.groupUpdates} onChange={value => set("groupUpdates", value)} rows={4} /><TextAreaField label="Events / trade activity" value={form.eventTradeActivity} onChange={value => set("eventTradeActivity", value)} rows={4} /><TextAreaField label="Completed actions" value={form.completedActions} onChange={value => set("completedActions", value)} rows={4} /><TextAreaField label="Next-week priorities" value={form.nextWeekPriorities} onChange={value => set("nextWeekPriorities", value)} rows={4} /></div><DialogActions onCancel={() => setEditorOpen(false)} saving={create.isPending || update.isPending} disabled={!form.propertyId || !form.ownerId || !form.weekCommencing} submitLabel={editingId ? "Save update" : "Create draft"} /></form></DialogContent></Dialog>

    <CRMDetailSheet open={selected !== null} onOpenChange={open => !open && setSelected(null)} title={selected ? `Week of ${shortDate(selected.weekCommencing)}` : "Weekly update"} eyebrow={selected?.propertyName || "Property commercial summary"} action={canEditSelected ? <Button size="sm" onClick={() => openEdit()} className="rounded-xl"><Pencil className="mr-2 h-3.5 w-3.5" />Edit</Button> : undefined}>{selected && <div className="space-y-6"><div className="rounded-2xl bg-[#002460] p-5 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><PropertyLogo propertyName={selected.propertyName} /><div><p className="text-[9px] font-semibold uppercase tracking-[0.17em] text-[#6cccd8]">{selected.status}</p><h3 className="mt-1 text-lg font-semibold">{selected.propertyName}</h3><p className="mt-1.5 text-xs text-white/65">{selected.ownerName} · Week commencing {shortDate(selected.weekCommencing)}</p></div></div></div><div className="grid gap-2 sm:grid-cols-2"><DetailPair label="Key wins" value={selected.keyWins} wide /><DetailPair label="Business potential" value={selected.businessPotential} wide /><DetailPair label="Key activity" value={selected.keyActivity} wide /><DetailPair label="Corporate updates" value={selected.corporateUpdates} wide /><DetailPair label="Group updates" value={selected.groupUpdates} wide /><DetailPair label="Events / trade activity" value={selected.eventTradeActivity} wide /><DetailPair label="Completed actions" value={selected.completedActions} wide /><DetailPair label="Next-week priorities" value={selected.nextWeekPriorities} wide /></div><div className="flex items-center justify-between rounded-2xl border border-[#dce5ee] bg-[#f7fafc] p-4"><div className="flex items-center gap-3"><Eye className="h-4 w-4 text-[#00758f]" /><div><p className="text-xs font-semibold">{selected.isGroupVisible ? "Group visible" : "Private update"}</p><p className="mt-1 text-[9px] text-muted-foreground">{selected.status === "Submitted" ? `Submitted ${shortDate(selected.submittedAt)}` : "Submit to include this in reporting"}</p></div></div><StatusBadge value={selected.status} /></div>{canEditSelected && selected.status === "Draft" && <Button onClick={() => submitUpdate.mutate({ id: selected.id })} disabled={submitUpdate.isPending} className="w-full rounded-xl"><Send className="mr-2 h-4 w-4" />Submit weekly update</Button>}{selected.status === "Submitted" && <div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" />This update is included in commercial reporting.</div>}</div>}</CRMDetailSheet>
  </div>;
}

function inputDate(value: Date) { return new Date(value).toISOString().slice(0, 10); }
function mondayInput(value: Date) { const date = new Date(value); const day = date.getDay(); const distance = day === 0 ? -6 : 1 - day; date.setDate(date.getDate() + distance); return inputDate(date); }
